name: deploy-static-site
on:
  push:
    branches:
      - 'master'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: |
          git remote set-url origin https://jeremygiberson:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git config --global user.email jeremygiberson@gmail.com
          git config --global user.name gh-action-deploy
          npm install
          npm run deploy