name: deploy-static-site
on:
  push:
    branches:
      - 'master'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install
      - run: npm run deploy